// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTodo = "todos"

// Todo mapped from table <todos>
type Todo struct {
	ID          string  `gorm:"column:id;primaryKey" json:"id"`
	Name        *string `gorm:"column:name" json:"name"`
	Description *string `gorm:"column:description" json:"description"`
	Completed   *bool   `gorm:"column:completed" json:"completed"`
}

// TableName Todo's table name
func (*Todo) TableName() string {
	return TableNameTodo
}
